# Generated by Django 4.2.25 on 2025-11-06 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0002_usuario_telefone_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacao', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('moeda', models.CharField(default='BRL', max_length=10)),
                ('valor_atual', models.FloatField(default=0)),
                ('alta_dia', models.FloatField(default=0)),
                ('baixa_dia', models.FloatField(default=0)),
                ('percentual_mudanca', models.FloatField(default=0)),
                ('variacao', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('preco_abertura', models.FloatField(default=0)),
                ('preco_anterior', models.FloatField(default=0)),
                ('faixa_dia', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.FloatField(default=0)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('industria', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['abreviacao'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('industria', models.CharField(blank=True, max_length=100, null=True)),
                ('funcionarios', models.IntegerField(blank=True, null=True)),
                ('descricao_longa', models.TextField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('acao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='tela_cadastro.acao')),
            ],
            options={
                'verbose_name': 'Perfil da Empresa',
                'verbose_name_plural': 'Perfis das Empresas',
            },
        ),
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(default=0)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ultima_data_prior', models.DateField(blank=True, null=True)),
                ('aprovado_em', models.DateField(blank=True, null=True)),
                ('isin_code', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividendos', to='tela_cadastro.acao')),
            ],
            options={
                'verbose_name': 'Dividendo',
                'verbose_name_plural': 'Dividendos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='AcaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('abertura', models.FloatField(default=0)),
                ('fechamento', models.FloatField(default=0)),
                ('alta', models.FloatField(default=0)),
                ('baixa', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('variacao', models.FloatField(blank=True, null=True)),
                ('periodo', models.CharField(default='1d', max_length=10)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='tela_cadastro.acao')),
            ],
            options={
                'verbose_name': 'Histórico da Ação',
                'verbose_name_plural': 'Históricos das Ações',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='acao',
            index=models.Index(fields=['abreviacao'], name='tela_cadast_abrevia_4de58f_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendo',
            index=models.Index(fields=['acao', 'data_pagamento'], name='tela_cadast_acao_id_4003b0_idx'),
        ),
        migrations.AddIndex(
            model_name='acaohistorico',
            index=models.Index(fields=['acao', 'data'], name='tela_cadast_acao_id_cef9c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acaohistorico',
            unique_together={('acao', 'data', 'periodo')},
        ),
    ]
