# Generated by Django 4.2.25 on 2025-11-08 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0003_acao_empresaperfil_dividendo_acaohistorico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('preco_alvo', models.FloatField()),
                ('direcao', models.CharField(choices=[('acima', 'Acima'), ('acima_ou_igual', 'Acima ou Igual'), ('abaixo', 'Abaixo'), ('abaixo_ou_igual', 'Abaixo ou Igual')], max_length=20)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tela_cadastro.acao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
