# Generated by Django 4.2.25 on 2025-11-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0004_monitoramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaohistorico',
            name='periodo',
            field=models.CharField(choices=[('1d', '1 Dia'), ('5d', '5 Dias'), ('1mo', '1 Mês'), ('3mo', '3 Meses'), ('6mo', '6 Meses'), ('1y', '1 Ano'), ('2y', '2 Anos'), ('5y', '5 Anos'), ('10y', '10 Anos'), ('ytd', 'Ano Corrente'), ('max', 'Máximo')], default='1d', help_text='Intervalo dos dados históricos conforme BRAPI', max_length=10),
        ),
    ]
