# Generated by Django 4.2.25 on 2025-11-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0005_alter_acaohistorico_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividendo',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='empresaperfil',
            name='acao',
        ),
        migrations.AlterModelOptions(
            name='acaohistorico',
            options={'verbose_name': 'Perfil da Empresa', 'verbose_name_plural': 'Perfis das Empresas'},
        ),
        migrations.RemoveIndex(
            model_name='acaohistorico',
            name='tela_cadast_acao_id_cef9c2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='acaohistorico',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Dividendo',
        ),
        migrations.DeleteModel(
            name='EmpresaPerfil',
        ),
    ]
