# Generated by Django 4.2.25 on 2025-11-26 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0006_remove_dividendo_acao_remove_empresaperfil_acao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('preco', 'Preço'), ('percentual', 'Percentual'), ('volume', 'Volume'), ('market_cap', 'Market Cap')], max_length=20)),
                ('valor_referencia', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
                ('disparado', models.BooleanField(default=False)),
                ('disparado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tela_cadastro.acao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('sistema', 'Sistema'), ('dividendo', 'Dividendo'), ('informativo', 'Informativo')], max_length=50)),
                ('lida', models.BooleanField(default=False)),
                ('enviada_telegram', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tela_cadastro.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'lida'], name='tela_cadast_usuario_d65d0f_idx'), models.Index(fields=['enviada_telegram'], name='tela_cadast_enviada_49ddb7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['usuario', 'acao'], name='tela_cadast_usuario_c6635c_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['ativo', 'disparado'], name='tela_cadast_ativo_68df27_idx'),
        ),
    ]
