# Generated by Django 4.2.25 on 2025-11-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0006_remove_dividendo_acao_remove_empresaperfil_acao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
