# Generated by Django 4.2.25 on 2025-11-23 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tela_cadastro', '0007_usuario_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
                ('is_leader', models.BooleanField(default=False)),
                ('uptime_segundos', models.BigIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
